#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Interactive `.env` wizard — pure Bash, zero dependencies. Inspired by
# vigenair's Node.js prompts flow. Reads defaults from .env.example (if
# present) or from ENV, prompts the operator for each key, writes .env.
#
# Usage:
#   bash infra/contexts/deploy/application/wizard.sh
# Or via Make:
#   make wizard

set -uo pipefail
cd "$(dirname "$0")/../../../.."  # repo root

if [ -t 1 ]; then
  B=$(tput bold); D=$(tput dim); G=$(tput setaf 2); Y=$(tput setaf 3); N=$(tput sgr0)
else
  B=""; D=""; G=""; Y=""; N=""
fi

# --- Preflight: does .env already exist? ---
if [ -f .env ]; then
  echo "${Y}⚠${N} .env already exists. Values below default to your current .env."
  echo "  Press Enter to keep each existing value, or type a new one to override."
  echo ""
  # Source it into this shell so defaults come from user's current .env
  set +u
  . ./.env 2>/dev/null || true
  set -u
elif [ -f .env.example ]; then
  echo "${D}→ Reading defaults from .env.example${N}"
  set +u
  . ./.env.example 2>/dev/null || true
  set -u
fi

# ---------- helpers ----------

# prompt VAR "prompt text" ["default"]
prompt() {
  local var="$1" msg="$2" default="${3:-}"
  local current="${!var:-$default}"
  local suffix=""
  [ -n "$current" ] && suffix="${D}[${current}]${N}"
  local reply
  # -r so backslashes don't get escaped; -e so arrow keys work in bash
  read -r -e -p "  ${msg} ${suffix}: " reply
  if [ -z "$reply" ]; then
    printf -v "$var" '%s' "$current"
  else
    printf -v "$var" '%s' "$reply"
  fi
}

# yn VAR "prompt text" ["y"|"n"]
yn() {
  local var="$1" msg="$2" default="${3:-n}"
  local reply
  read -r -p "  ${msg} [$([ "$default" = "y" ] && echo "Y/n" || echo "y/N")]: " reply
  reply="${reply:-$default}"
  case "$reply" in
    [yY]|[yY][eE][sS]) printf -v "$var" 'true' ;;
    *) printf -v "$var" 'false' ;;
  esac
}

# ---------- prompts ----------

echo ""
echo "${B}==> GE Observability wizard${N}"
echo ""

echo "${B}Required${N}"
prompt BQ_PROJECT "GCP project ID (the one running GE)" "${BQ_PROJECT:-}"
if [ -z "$BQ_PROJECT" ]; then
  echo "${Y}✗${N} BQ_PROJECT is required — aborting."
  exit 1
fi
# PROJECT is a Makefile alias for BQ_PROJECT
PROJECT="$BQ_PROJECT"

echo ""
echo "${B}Region + dataset${N}"
prompt REGION "Region for Cloud Run + Artifact Registry" "${REGION:-us-central1}"
# BQ_LOCATION defaults to REGION so single-region setups auto-co-locate (INV-001)
prompt BQ_LOCATION "BigQuery dataset location (Enter to co-locate with REGION)" "${BQ_LOCATION:-$REGION}"
prompt DATASET "BigQuery dataset name" "${DATASET:-ge_observability}"
BQ_DATASET="$DATASET"

echo ""
echo "${B}Optional${N}"
prompt SIM_PREFIX "Actor-email prefix to strip at query time (leave 'sim-' if unsure)" "${SIM_PREFIX:-sim-}"
prompt PORT "Uvicorn port for local preview" "${PORT:-8000}"

# ---------- write .env ----------

echo ""
if [ -f .env ]; then
  cp .env .env.bak
  echo "${D}→ Backed up existing .env to .env.bak${N}"
fi

cat > .env <<EOF
# Generated by \`make wizard\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Re-run the wizard any time to update.

BQ_PROJECT=${BQ_PROJECT}
PROJECT=${PROJECT}

BQ_DATASET=${BQ_DATASET}
DATASET=${DATASET}

REGION=${REGION}
BQ_LOCATION=${BQ_LOCATION}

SIM_PREFIX=${SIM_PREFIX}
PORT=${PORT}

# GOOGLE_APPLICATION_CREDENTIALS=/path/to/sa-key.json   # uncomment if using SA key
EOF

echo "${G}✓${N} Wrote .env"
echo ""
echo "${B}Next steps${N}"
echo "  1. ${D}gcloud auth application-default login${N}   (if \`make doctor\` reports ADC missing)"
echo "  2. ${D}make deploy-infra${N}                        (needs project Owner — see docs/DEPLOYMENT.md)"
echo "     ${D}or: make serve${N}                           (local preview if BQ dataset already exists)"
